class Screens:
    WELCOME = ["Welcome at", "{instrument_name}", "Please scan your card."]
    CHECKING_USER = ["Checking user"]
    CHECKING_RESERVATION = ["Checking reservation"]
    CHECKING_TOKEN = ["Checking token"]
    IN_SESSION = ["Recording is running", "Remaining time:{remaining_session_time}"]
    USER_OK = ["Hi", "{user_name}", "{random_phrase}"]
    USER_NOK = ["User validation failed"]
    RESERVATION_OK = ["Reservation confirmed"]
    RESERVATION_NOK = ["Reservation not found"]
    BUTTON_MENU = ["Press a button to continue"]
    RESERVATION_PROLONGED = ["Reservation prolonged"]
    SESSION_ENDED_BY_USER = ["Session ended by user"]
    SESSION_ENDED = ["Session ended"]
